{% set name = "burr" %}
{% set version = "0.33.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/burr-{{ version }}.tar.gz
  sha256: 7bc49cf6a86be80c8fd4d6e1bf7f257539bef7797047f0f84ecdd8c592800d28

build:
  entry_points:
    - burr = burr.cli.__main__:cli_run_server
    - burr-demo = burr.cli.__main__:cli_demo_server
    - burr-admin-server = burr.cli.__main__:cli_run_server
    - burr-admin-publish = burr.cli.__main__:cli_build_and_publish
    - burr-admin-build-ui = burr.cli.__main__:cli_build_ui
    - burr-admin-generate-demo-data = burr.cli.__main__:cli_generate_demo_data
    - burr-test-case = burr.cli.__main__:cli_test_case
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - burr
  commands:
    - pip check
    - burr --help
    - burr-demo --help
    - burr-admin-server --help
    - burr-admin-publish --help
    - burr-admin-build-ui --help
    - burr-admin-generate-demo-data --help
    - burr-test-case --help
  requires:
    - python {{ python_min }}
    - pip
    - aiofiles
    - click
    - fastapi
    - fastapi-pagination
    - fastapi_utils
    - graphviz
    - jinja2
    - loguru
    - matplotlib
    - openai
    - pydantic
    - pydantic-settings
    - requests
    - sf-hamilton
    - streamlit
    - uvicorn

about:
  summary: A state machine for data projects
  home: https://github.com/dagworks-inc/burr
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
